### ISSUE TITLE
RadxBufr path to share hardcoded

### ISSUE THREAD

**Issue by swnesbitt** [NCAR/lrose-core#22]
[I'm working with Argentinian Radar for the RELAMPAGO project, so I am happy to be a beta tester on the new RadxBufr tool]

I was able to build RadxBufr - works with some issues.  I'll report things as I see them.  First issue: found that the path to the bufr tables, i.e., `../share/bbufr/tables/bufrtabb_16.csv` is hard coded - should be relative to the executable path, correct?

Also, the tables were not included when i cloned from github, but I have them from my Argentinian colleagues...

**Comment by leavesntwigs** [comment]
Right.  First, though, thank you for using the RadxBufr code!  I have just pushed a version of RadxBufr that contains internal versions of the BUFR tables.  These are probably the same versions that you have,  since I obtained them from Argentinian colleagues as well.  I have also added a command line option '-tables' followed by a path to a directory containing BUFR tables.  Hope this is of use.
