### ISSUE TITLE
ld: cannot find -lNcxx

### ISSUE THREAD

**Issue by juhi24** [NCAR/lrose-core#25]
I'm trying to install the `radx-20171016.src` release on ubuntu 16.04. I succesfully installed the supplied netcdf in the default directory using `build_and_install_netcdf`, but it seems ld still cannot find a library called Ncxx. What is this library actually? The build command I used was:
```
$ LD_LIBRARY_PATH=/usr/local/lrose/lib sudo build/build_auto -p radx -x /usr/local
```

**Comment by mjskier** [comment]
libNcxx is the C++ interface to Netcdf.

The problem is that environment variables don't survive sudo.

Try this:
LD_LIBRARY_PATH=/tmp/foo sudo printenv | grep LD_LIBR
You won't find LD_LIBRARY_PATH

You could try the -E option of sudo (--preserve-env). But honestly,
building things with sudo isn't exactly considered a "best practice"

Bruno.

**Comment by juhi24** [comment]
Thanks. I used sudo since I wasn't sure if the script would also try to install the compiled result. I eventually got the binary release working, so I stopped trying to compile. This issue can be closed.
