### ISSUE TITLE
checkout_and_build_auto error

### ISSUE THREAD

**Issue by toddstellies** [NCAR/lrose-core#47]
Hi 

I am trying to build lrose, (specifically titan). I am making use of the auto build file (checkout_and_build_auto.py from lrose build) and the following error spits out:
"
...
considering: /tmp/lrose_build/lrose-core/codebase/apps/trec/src/ptrec.udp
discarding it
considering: /tmp/lrose_build/lrose-core/codebase/apps/trec/Makefile
considering: /tmp/lrose_build/lrose-core/codebase/apps/trec/CVS
discarding it
considering: /tmp/lrose_build/lrose-core/codebase/apps/trec/test
discarding it
considering: /tmp/lrose_build/lrose-core/codebase/apps/trec/.cvsignore
Traceback (most recent call last):
  File "./checkout_and_build_auto.py", line 578, in <module>
    main()
  File "./checkout_and_build_auto.py", line 169, in main
    setupAutoconf()
  File "./checkout_and_build_auto.py", line 271, in setupAutoconf
    "./configure.base.shared")
  File "/home/todd/anaconda2/lib/python2.7/shutil.py", line 133, in copy
    copyfile(src, dst)
  File "/home/todd/anaconda2/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '../build/configure.base.shared'
"

I have checked the directory 'build' and there is a file called 'configure.base.shared'

Please help

**Comment by mjskier** [comment]
I assume Lunix? Which distribution?

I have no such issue on a Debian based machine. The only obvious difference is that I am using the system installed python instead of the one that comes with anaconda.

Speaking of anaconda, it comes with its own version of qmake (at least anaconda3 does, not sure about anaconda2) and for me that causes issues with qt5. So when I use the checkout_and_buid_auto.py script I restrict PATH to just a few known location:

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /usr/bin/python ./checkout_and_build_auto.py ...
```
