### ISSUE TITLE
MacOSX binary install problem

### ISSUE THREAD

**Issue by nguy** [NCAR/lrose-core#56]
I am able to complete the install of the MacOS binary  from April (there are no other later mac binary releases I could find) using
```
(radview) bguy:lrose-20180430.bin.mac_osx $ ./install_bin_release.py --prefix /Users/bguy/software/radar/lrose
```

However I get the following output message that suggests that buried somewhere there is a hard-coded link for libraries, since you note from above I set a specific prefix. 
```
RadxConvert -f KLBB20180727_160528_V06 
dyld: Library not loaded: /usr/local/lrose/lib/libFiltAlg.0.dylib
  Referenced from: /Users/bguy/software/radar/lrose/bin/RadxConvert
  Reason: image not found
```

Maybe this is fixed in a later release?

**Comment by mjskier** [comment]
There is a 07/05 pre-release. I haven't tried the bin release, but building from source works.

Binary releases are a bad idea because with limited resources it is too hard to support the multiple versions of McOS and Linux, available.

I would suggest building from source ./build_src_release.py --prefix=....

And if you only care about HawkEye, Radx2Grid, RadxConvert, and RadxPrint, you could try the lrose-blaze release which is a lot smaller than the full lrose distribution:
https://nsf-lrose.github.io/

**Comment by nguy** [comment]
Thanks @mjskier , see #54 for all the fun I had the other day. :)
