### ISSUE TITLE
Errors of Radx2Grid

### ISSUE THREAD

**Issue by hhuangwx** [NCAR/lrose-core#74]
Hi, 

I'm not sure about the reason, but lots of errors occurred when I use Radx2Grid to get the Cartesian gridded data.

Apparently, azimuthal discontinuity exists in different altitudes. Anyone who knows the reason, please help me. The parameter file utilized is also attached as "Radx2GridTunned.txt".

![image](https://user-images.githubusercontent.com/11309009/59271084-ad725100-8c85-11e9-9e88-9e58b416c5b3.png)

![image](https://user-images.githubusercontent.com/11309009/59270934-4a80ba00-8c85-11e9-8553-b37c4f5a4bc8.png)

![image](https://user-images.githubusercontent.com/11309009/59271105-b6632280-8c85-11e9-87e2-05c3b0541494.png)

[Radx2GridTunned.txt](https://github.com/NCAR/lrose-core/files/3276412/Radx2GridTunned.txt)

**Comment by mike-dixon** [comment]
The problem comes from NEXRAD data, in super-res mode, having 0.5 degree azimuth spacing for long-range rays and 1.0 degree spacing for short-range rays.
When processing NEXRAD data, you need to make sure that the long range rays are merged with the short range sweeps, rather than preserving the sweeps as they exist in the NEXRAD file.
We suggest that you first use RadxConvert to convert from NEXRAD to CfRadial, and ensure that preserve_sweeps is set to FALSE. Then Radx2Grid should not produce the stripes seen in these images.
If you use Radx2Grid directly on NEXRAD data, ensure remove_long_range_rays is FALSE.
